server:
  port: 8080
nacos:
  config:
    server-addr: localhost:8848
    namespace:
    max-retry: 3
    config-long-poll-timeout: 1000
    config-retry-time: 1000
    auto-refresh: true
    username: nacos
    password: nacos
    context-path: /nacos
    group: DEFAULT_GROUP
    file-extension: yaml
spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 1MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace:
        service: gateway
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: test-url-proxy
          uri: lb://platform
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: sys-url-proxy
          uri: lb://platform
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: data-url-proxy
          uri: lb://platform
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: share-url-proxy
          uri: lb://platform
          predicates:
            - Path=/share/**
          filters:
            - StripPrefix=1
            - BaseParam
            - SysAuth
            - SysLog
        - id: swagger-url-proxy
          uri: lb://platform
          predicates:
            - Path=/platform/**
          filters:
            - StripPrefix=1
#            - BaseParam
            - Swagger
            - SysAuth
#            - SysLog

logging:
  level:
    root: debug
  config: classpath:logback-privacy.xml